config/routes.rb
Rails.application.routes.draw do

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resources :genres 

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :characterizations, dependent: :destroy 
  has_many :movies, through: :characterizations

  validates :name, presence: true,
    uniqueness: { case_sensitive: false } 

  before_save :set_slug

  def to_param 
    slug 
  end
  private 

  def set_slug 
    self.slug = name.parameterize 
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :require_signin, except: [:index, :show] 
  before_action :require_admin, except: [:index, :show]
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  def index 
    @genres = Genre.all.order(:name)
  end

  def new 
    @genre = Genre.new()
  end

  def create 
    @genre = Genre.new(genre_params)
    if @genre.save 
      redirect_to @genre, message: "Genre '#{@genre.name}' successfully added!"
    else 
      render :new, status: :unprocessable_entity
    end
  end 

  def show
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre, notice: "Genre '#{@genre.name}' successfully updated!" 
    else 
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.destroy 
    redirect_to genres_path, status: :see_other, alert: "Genre '#{@genre.name}' successfully deleted!"
  end

  private 

  def set_genre
    @genre = Genre.find_by!(slug: params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.html.erb
<%= form_with(model: genre) do |f| %> 
  <%= render 'shared/errors', object: genre %>

  <%= f.label :name %> 
  <%= f.text_field :name, autofocus: true %> 

  <%= f.submit %>
<% end %>

app/views/genres/edit.html.erb
<h1>Edit genre '<%= @genre.name %>'.</h1>
<%= render "form", genre: @genre %>

app/views/genres/index.html.erb
<h1>Genres</h1>
<ul>
  <% @genres.each do |genre| %>
    <li><%= link_to genre.name, genre %></li>
  <% end %>
</ul>
<% if current_user_admin? %>
  <section class="admin">
    <%= link_to "Add New Genre", new_genre_path(@genre), class: "button" %>
  </section> 
<% end %> 

app/views/genres/new.html.erb
<h1>Add a new genre.</h1>
<%= render "form", genre: @genre %>

app/views/genres/show.html.erb
<h1><%= @genre.name %> movies</h1>
<% if current_user_admin? %>
  <section class="admin genre-admin">
    <p>As an admin, you can edit or delete this genre.</p>
    <%= link_to "Edit", edit_genre_path(@genre), class: "button" %> 
    <%= link_to "Delete", genre_path(@genre), class: "button",
          data: { turbo_method: :delete, turbo_confirm: "This action cannot be undone. Are you sure?" } %> 
  </section>
<% end %>
<% @genre.movies.each do |movie| %>
  <section class="movie">
    <div class="image">
      <%= image_tag movie.image_file_name %>
    </div>
    <div class="summary">
      <h2>
        <%= link_to movie.title, movie %>
      </h2>
      <h3>
        <%= total_gross(movie) %>
      </h3>
      <span class="stars">
        <%= render "shared/stars", percent: movie.average_stars_as_percent %>
      </span>
      <p>
        <strong>Director:</strong> <%= movie.director %> <br />
        <strong>Duration:</strong> <%= movie.duration %> <br />
      </p>
      <p>
        <%= truncate(movie.description, length: 150, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>