config/routes.rb
Rails.application.routes.draw do

  root "movies#index"

  get "movies/filter/:filter" => "movies#index", as: :filtered_movies

  resources :movies do 
    resources :reviews
    resources :favorites, only: [:create, :destroy]
  end

  resources :genres 

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"

  resources :users
  get "signup" => "users#new"

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright &copy;<%= Time.now.year %>
  <%= link_to "Flix Web App", "/" %>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
      <li><%= link_to "All movies", movies_path %></li>
      <li><%= nav_link_to("Recent", filtered_movies_path(:recent)) %></li>
      <li><%= nav_link_to("Upcoming", filtered_movies_path(:upcoming)) %></li>
      <li><%= nav_link_to("Released", filtered_movies_path(:released)) %></li>
      <li><%= nav_link_to("Hits", filtered_movies_path(:hits)) %></li>
      <li><%= nav_link_to("Flops", filtered_movies_path(:flops)) %></li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li><%= link_to current_user.name, current_user %></li>
        <li><%= link_to 'Account settings', edit_user_path(current_user) %></li>
        <li><%= link_to "Sign out", session_path, class: "button",
                                    data: { turbo_method: :delete, notice: "You have successfully signed out." } %></li>
      <% else %>
        <li><%= link_to "Sign in", signin_path, class: "button" %></li>
        <li><%= link_to "Sign up!", signup_path, class: "button" %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix Web App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <%= render "layouts/header" %>
  
  <body>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>

  <%= render "layouts/footer" %>

</html>